### ISSUE TITLE
Uncaught TypeError: this.setCursor is not a function

### ISSUE THREAD

**Issue by phet-steele** [phetsims/energy-skate-park-basics#373]
From phetsims/scenery/issues/629

```
Uncaught TypeError: this.setCursor is not a function
    at RoundPushButton.set cursor [as cursor] (Node.js?bust=1499447782666:2981)
    at Array.<anonymous> (RoundButtonView.js?bust=1499447782666:117)
    at Emitter.emit2 (Emitter.js?bust=1499447782666:147)
    at PushButtonInteractionStateProperty._notifyObservers (Property.js?bust=1499447782666:207)
    at PushButtonInteractionStateProperty._setAndNotifyObservers (Property.js?bust=1499447782666:196)
    at PushButtonInteractionStateProperty.set (Property.js?bust=1499447782666:140)
    at Array.listener (DerivedProperty.js?bust=1499447782666:67)
    at Emitter.emit2 (Emitter.js?bust=1499447782666:147)
    at Property._notifyObservers (Property.js?bust=1499447782666:207)
    at Property._setAndNotifyObservers (Property.js?bust=1499447782666:196)
```

**Comment by jonathanolson** [comment]
Looks like an issue in RoundButtonView, where it is still listening to the property and modifying the node after disposal:
```js
    interactionStateProperty.link( function( state ) {
      self.cursor = state === 'disabled' || state === 'disabled-pressed' ? null : 'pointer';
    } );
```

@jbphet, is it safe for me to add a dispose() function that unlinks this listener?

**Comment by jbphet** [comment]
Yes, it should be safe to add such a dispose function.  It appears that it is already called in `RoundPushButton`, so there is a decent chance that adding this will fix the problem.

**Comment by jbphet** [comment]
This was easy to duplicate on ESPB - the user just had to go to the third screen, create a track with two pieces, click on the junction, and then press the button for cutting the pieces apart.  I've added the dispose function, and the assertion no longer occurs.

**Comment by jbphet** [comment]
Some of the changes to Scenery that initially motivated the changes shown in the commits above have been backed out, but I reviewed these changes and I think that they are still an improvement.  The appearance strategies are now objects, which is probably easier for future maintainers to understand, and they have dispose functions that should help to avoid memory leaks.

Since this is common code, it probably should be reviewed.  @ariel-phet happened to walk into the room as I was writing this, so I asked him who should review it.  I estimated it would take 1/2 hr to review.  He said I should assign to @pixelzoom, since he has the most experience with dispose functions and such.  However, if this turns into a 'rathole' and would take longer to review than 1/2 hr, @pixelzoom should stop, note his findings, and move on and we will go from there.

**Comment by pixelzoom** [comment]
Not clear what you'd like me to review here.  I see a commit above for RoundButtonView, @44418740835b153ef87c726ba99cd6c519e06d3e. But I see similar commits to RectangularButtonView and RadioButtonAppearanceGroup in @bf7d0d8760b02942f15accd5399da0997dc44980.  And I suspect that there may be others.  Which UI components do you want reviewed, and what is the list of commits?

**Comment by pixelzoom** [comment]
@ariel-phet 15 minutes into this so far.

**Comment by pixelzoom** [comment]
It would also be nice if you could summarize what changes were made and why, so I don't have to figure it out from diffs.

**Comment by jbphet** [comment]
These two should cover it:
https://github.com/phetsims/sun/commit/44418740835b153ef87c726ba99cd6c519e06d3e
https://github.com/phetsims/sun/commit/bf7d0d8760b02942f15accd5399da0997dc44980

**Comment by jbphet** [comment]
Please scan and, if they look like more than 1/2 hr, just abort and I'll discuss with @ariel-phet.

**Comment by jbphet** [comment]
Summary of what was done: I changed the 'appearance strategies' that are used to control what the buttons look like and what happens to their content when enabled/disabled to be instantiated objects instead of functions and to have dispose functions that allow them to be unhooked from the properties that they monitor.

**Comment by pixelzoom** [comment]
I don't see anything obviously wrong. Looks like good changes.

**Comment by jbphet** [comment]
Thanks for the review @pixelzoom - closing.
