### ISSUE TITLE
Discarding thermal energy leaves dot behind

### ISSUE THREAD

**Issue by rea-laura** [phetsims/energy-skate-park-basics#449]
<b>Test Device</b>

Jordan

<b>Operating System</b>

Mojave 10.14.2

<b>Browser</b>

Chrome 71.0.3578.98

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/226:
When all of the energy is consumed into thermal energy, discarding the thermal energy leaves behind a dot.

<b>Steps to Reproduce</b>

Method 1 - leaves dot with no energy left in bar graph
1) Go to energy skate park basics from phettest.colorado.edu
2) Select "Friction" page from the home menu
3) Set friction to "lots"
4) turn on pie chart and bar graph
5) drop skater on track and let them oscillate until all energy is converted into thermal. Wait a few seconds for skater to completely stop.
6) press the trash can by the thermal energy in the graph key to discard thermal energy
7) a dot will be left behind floating over the head of the skater, but no energy is left in the bar graph (image 1). Dot will also move when you adjust the size of the skater.

Method 2 - dot left behind with energy left in graph
1) using the same settings, place the skater in the bottom of the curve so it won't move.
2) grab the dot under the skater and move it slightly to one side. Release so it rolls down just a little bit
3) while the skater is still moving slightly, discard the thermal energy using the trash can button. Press trash can button repeatedly until it becomes inactivated.
4) energy will still be left behind in the graph (small amount of thermal and total) and a dot will be left above skater's head (image 2).

Method 2 - control. Leaves no dot above skater's head
1) with all the same settings on, drop the skater onto level ground
2) discard thermal energy
3) no dot above the skater's head (image 3)

<b>Visuals</b>

Image 1: dot above head, no energy in graph
![screen shot 2018-12-18 at 10 21 10 am](https://user-images.githubusercontent.com/44005544/50171958-241f2a80-02b1-11e9-9af9-763682445d96.png)

Image 2: dot above head, energy left in graph
![screen shot 2018-12-18 at 10 33 40 am](https://user-images.githubusercontent.com/44005544/50171977-31d4b000-02b1-11e9-9e3f-cda91f0ea420.png)

Image 3: no dot
![screen shot 2018-12-18 at 10 33 53 am](https://user-images.githubusercontent.com/44005544/50172006-40bb6280-02b1-11e9-98e1-981a5e86bebf.png)

**Comment by samreid** [comment]
Thanks @rea-laura, I'm also assigning @jessegreenberg so he's aware of it and in case he addresses it before I get here.

**Comment by jessegreenberg** [comment]
Sounds good - I took a look and here is what I found:

- Method 1: Currently on master the opposite happens. The pie chart dot is not there but there is a small amount of thermal/total energy in the graph. If anything, I think to be consistent a dot SHOULD appear as energy in the bar chart is expected for these reasons:
  - After oscillation, skater doesn't every fully stop. Skater oscillation continues indefinitely with kinetic, thermal, and potential energy in the model even though it cannot be seen.
  - While this happens, kinetic energy continues to convert to thermal energy.
  - To address the pedagogical goal of "The kinetic energy is zero at the top of the trajectory (turning point), potential energy is zero at bottom" we hide small kinetic/potential energies in the bar graph.
  - We made sure that as long as there was non-zero energy in the system, total and thermal energy bars were large enough to be visible on the graph (https://github.com/phetsims/energy-skate-park/issues/160)
- Method 2: I get the same behavior as method 1 now on master. No pie chart with some energy shown in the bar graph.
- Method 3: This is expected behavior as well. Without oscillation there is no kinetic energy to convert to thermal.

**Comment by jessegreenberg** [comment]
I found https://github.com/phetsims/energy-skate-park-basics/issues/136 where the following was introduced to make the pie chart invisible when energies are too low.

```js
        // If any value is too low, then don't show it, see #136
        const THRESHOLD = 1E-4;

        // if only one component of pie chart, then show as a circle so there are no seams
        const numberComponents = ( skater.potentialEnergyProperty.value > THRESHOLD ? 1 : 0 ) +
                               ( skater.kineticEnergyProperty.value > THRESHOLD ? 1 : 0 ) +
                               ( skater.thermalEnergyProperty.value > THRESHOLD ? 1 : 0 );
```

So I would recommend that we don't do anything further for this issue. The original issue report (no energy in bar graph, energy showed in pie chart) was definitely an issue. But that is no longer what is happening and issue history and https://github.com/phetsims/energy-skate-park-basics/issues/449#issuecomment-572297248 demonstrate that sim is currently working as expected.

Closing.
